export const GCP_CHIRP3_VOICES = [
  'en-US-Chirp3-HD-Achernar',
  'en-US-Chirp3-HD-Achird',
  'en-US-Chirp3-HD-Algenib',
  'en-US-Chirp3-HD-Algieba',
  'en-US-Chirp3-HD-Alnilam',
  'en-US-Chirp3-HD-Aoede',
  'en-US-Chirp3-HD-Autonoe',
  'en-US-Chirp3-HD-Callirrhoe',
  'en-US-Chirp3-HD-Charon',
  'en-US-Chirp3-HD-Despina',
  'en-US-Chirp3-HD-Enceladus',
  'en-US-Chirp3-HD-Erinome',
  'en-US-Chirp3-HD-Fenrir',
  'en-US-Chirp3-HD-Gacrux',
  'en-US-Chirp3-HD-Iapetus',
  'en-US-Chirp3-HD-Kore',
  'en-US-Chirp3-HD-Laomedeia',
  'en-US-Chirp3-HD-Leda',
  'en-US-Chirp3-HD-Orus',
  'en-US-Chirp3-HD-Puck',
  'en-US-Chirp3-HD-Pulcherrima',
  'en-US-Chirp3-HD-Rasalgethi',
  'en-US-Chirp3-HD-Sadachbia',
  'en-US-Chirp3-HD-Sadaltager',
  'en-US-Chirp3-HD-Schedar',
  'en-US-Chirp3-HD-Sulafat',
  'en-US-Chirp3-HD-Umbriel',
  'en-US-Chirp3-HD-Vindemiatrix',
  'en-US-Chirp3-HD-Zephyr',
  'en-US-Chirp3-HD-Zubenelgenubi',
] as const

export const GCP_CHIRP3_DEFAULT_VOICE = 'en-US-Chirp3-HD-Kore'

export const XAI_VOICES = ['Eve', 'Ara', 'Leo', 'Rex', 'Sal'] as const
export const XAI_DEFAULT_VOICE = 'Eve'

export const KOKORO_VOICES = [
  'af_alloy',
  'af_aoede',
  'af_bella',
  'af_heart',
  'af_jessica',
  'af_kore',
  'af_nicole',
  'af_nova',
  'af_river',
  'af_sarah',
  'af_sky',
  'am_adam',
  'am_echo',
  'am_eric',
  'am_fenrir',
  'am_liam',
  'am_michael',
  'am_onyx',
  'am_puck',
  'am_santa',
  'bf_alice',
  'bf_emma',
  'bf_isabella',
  'bf_lily',
  'bm_daniel',
  'bm_fable',
  'bm_george',
  'bm_lewis',
  'ef_dora',
  'em_alex',
  'em_santa',
  'ff_siwis',
  'hf_alpha',
  'hf_beta',
  'hm_omega',
  'hm_psi',
  'if_sara',
  'im_nicola',
  'jf_alpha',
  'jf_gongitsune',
  'jf_nezumi',
  'jf_tebukuro',
  'jm_kumo',
  'pf_dora',
  'pm_alex',
  'pm_santa',
  'zf_xiaobei',
  'zf_xiaoni',
  'zf_xiaoxiao',
  'zf_xiaoyi',
  'zm_yunjian',
  'zm_yunxi',
  'zm_yunxia',
  'zm_yunyang',
] as const
export const KOKORO_DEFAULT_VOICE = 'af_bella'

export const GPT_4O_MINI_TTS_VOICES = [
  'alloy',
  'ash',
  'ballad',
  'cedar',
  'coral',
  'echo',
  'fable',
  'marin',
  'nova',
  'onyx',
  'sage',
  'shimmer',
  'verse',
] as const
export const GPT_4O_MINI_TTS_DEFAULT_VOICE = 'coral'

export interface AzureVoiceInfo {
  name: string
  displayName: string
  locale: string
  gender: 'Female' | 'Male'
  style: string
  multilingual?: boolean
  tier: 'Neural' | 'Neural HD'
}

export const AZURE_VOICES: readonly AzureVoiceInfo[] = [
  {
    name: 'en-US-Ava:DragonHDLatestNeural',
    displayName: 'Ava HD',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Natural, conversational - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Andrew:DragonHDLatestNeural',
    displayName: 'Andrew HD',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Warm, engaged - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Aria:DragonHDLatestNeural',
    displayName: 'Aria HD',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Expressive, confident - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Brian:DragonHDLatestNeural',
    displayName: 'Brian HD',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Casual, lifelike - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Davis:DragonHDLatestNeural',
    displayName: 'Davis HD',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Warm, confident - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Emma:DragonHDLatestNeural',
    displayName: 'Emma HD',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Cheerful, natural - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Jenny:DragonHDLatestNeural',
    displayName: 'Jenny HD',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Considerate, natural - DragonHD',
    tier: 'Neural HD',
  },
  {
    name: 'en-US-Steffan:DragonHDLatestNeural',
    displayName: 'Steffan HD',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Rational, measured - DragonHD',
    tier: 'Neural HD',
  },
  { name: 'en-US-AmberNeural', displayName: 'Amber', locale: 'English (US)', gender: 'Female', style: 'Warm, friendly', tier: 'Neural' },
  { name: 'en-US-AnaNeural', displayName: 'Ana', locale: 'English (US)', gender: 'Female', style: 'Child voice, cute', tier: 'Neural' },
  { name: 'en-US-AndrewNeural', displayName: 'Andrew', locale: 'English (US)', gender: 'Male', style: 'Conversational, warm', tier: 'Neural' },
  {
    name: 'en-US-AndrewMultilingualNeural',
    displayName: 'Andrew (Multilingual)',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Conversational, multilingual',
    multilingual: true,
    tier: 'Neural',
  },
  { name: 'en-US-AriaNeural', displayName: 'Aria', locale: 'English (US)', gender: 'Female', style: 'Expressive, youthful', tier: 'Neural' },
  { name: 'en-US-AshleyNeural', displayName: 'Ashley', locale: 'English (US)', gender: 'Female', style: 'Expressive, youthful', tier: 'Neural' },
  { name: 'en-US-AvaNeural', displayName: 'Ava', locale: 'English (US)', gender: 'Female', style: 'Conversational, caring', tier: 'Neural' },
  {
    name: 'en-US-AvaMultilingualNeural',
    displayName: 'Ava (Multilingual)',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Conversational, multilingual',
    multilingual: true,
    tier: 'Neural',
  },
  { name: 'en-US-BrandonNeural', displayName: 'Brandon', locale: 'English (US)', gender: 'Male', style: 'Warm, approachable', tier: 'Neural' },
  {
    name: 'en-US-BrianNeural',
    displayName: 'Brian',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Casual, approachable, conversational',
    tier: 'Neural',
  },
  {
    name: 'en-US-BrianMultilingualNeural',
    displayName: 'Brian (Multilingual)',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Casual, multilingual',
    multilingual: true,
    tier: 'Neural',
  },
  {
    name: 'en-US-ChristopherNeural',
    displayName: 'Christopher',
    locale: 'English (US)',
    gender: 'Male',
    style: 'Reliable, authoritative',
    tier: 'Neural',
  },
  { name: 'en-US-CoraNeural', displayName: 'Cora', locale: 'English (US)', gender: 'Female', style: 'Thoughtful, calm', tier: 'Neural' },
  { name: 'en-US-DavisNeural', displayName: 'Davis', locale: 'English (US)', gender: 'Male', style: 'Warm, confident', tier: 'Neural' },
  { name: 'en-US-ElizabethNeural', displayName: 'Elizabeth', locale: 'English (US)', gender: 'Female', style: 'Cheerful, bright', tier: 'Neural' },
  {
    name: 'en-US-EmmaNeural',
    displayName: 'Emma',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Cheerful, positive, conversational',
    tier: 'Neural',
  },
  {
    name: 'en-US-EmmaMultilingualNeural',
    displayName: 'Emma (Multilingual)',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Cheerful, multilingual',
    multilingual: true,
    tier: 'Neural',
  },
  { name: 'en-US-EricNeural', displayName: 'Eric', locale: 'English (US)', gender: 'Male', style: 'Rational, matter-of-fact', tier: 'Neural' },
  { name: 'en-US-GuyNeural', displayName: 'Guy', locale: 'English (US)', gender: 'Male', style: 'Passionate, confident', tier: 'Neural' },
  { name: 'en-US-JacobNeural', displayName: 'Jacob', locale: 'English (US)', gender: 'Male', style: 'Rational, clear', tier: 'Neural' },
  { name: 'en-US-JaneNeural', displayName: 'Jane', locale: 'English (US)', gender: 'Female', style: 'Rational, clear', tier: 'Neural' },
  { name: 'en-US-JasonNeural', displayName: 'Jason', locale: 'English (US)', gender: 'Male', style: 'Casual, upbeat', tier: 'Neural' },
  { name: 'en-US-JennyNeural', displayName: 'Jenny', locale: 'English (US)', gender: 'Female', style: 'Considerate, friendly', tier: 'Neural' },
  {
    name: 'en-US-JennyMultilingualNeural',
    displayName: 'Jenny (Multilingual)',
    locale: 'English (US)',
    gender: 'Female',
    style: 'Considerate, multilingual',
    multilingual: true,
    tier: 'Neural',
  },
  { name: 'en-US-MichelleNeural', displayName: 'Michelle', locale: 'English (US)', gender: 'Female', style: 'Friendly, pleasant', tier: 'Neural' },
  { name: 'en-US-MonicaNeural', displayName: 'Monica', locale: 'English (US)', gender: 'Female', style: 'Friendly, warm', tier: 'Neural' },
  { name: 'en-US-NancyNeural', displayName: 'Nancy', locale: 'English (US)', gender: 'Female', style: 'Considerate, gentle', tier: 'Neural' },
  { name: 'en-US-RogerNeural', displayName: 'Roger', locale: 'English (US)', gender: 'Male', style: 'Lively, energetic', tier: 'Neural' },
  { name: 'en-US-SaraNeural', displayName: 'Sara', locale: 'English (US)', gender: 'Female', style: 'Cheerful, expressive', tier: 'Neural' },
  { name: 'en-US-SteffanNeural', displayName: 'Steffan', locale: 'English (US)', gender: 'Male', style: 'Rational, measured', tier: 'Neural' },
  { name: 'en-US-TonyNeural', displayName: 'Tony', locale: 'English (US)', gender: 'Male', style: 'Cool, relaxed', tier: 'Neural' },
]

export const AZURE_DEFAULT_VOICE = 'en-US-JennyNeural'

export const AZURE_REGIONS: readonly { code: string; label: string }[] = [
  { code: 'eastus', label: 'East US' },
  { code: 'eastus2', label: 'East US 2' },
  { code: 'westus', label: 'West US' },
  { code: 'westus2', label: 'West US 2' },
  { code: 'westus3', label: 'West US 3' },
  { code: 'centralus', label: 'Central US' },
  { code: 'northcentralus', label: 'North Central US' },
  { code: 'southcentralus', label: 'South Central US' },
  { code: 'westcentralus', label: 'West Central US' },
  { code: 'canadacentral', label: 'Canada Central' },
  { code: 'brazilsouth', label: 'Brazil South' },
  { code: 'northeurope', label: 'North Europe' },
  { code: 'westeurope', label: 'West Europe' },
  { code: 'swedencentral', label: 'Sweden Central' },
  { code: 'uksouth', label: 'UK South' },
  { code: 'francecentral', label: 'France Central' },
  { code: 'germanywestcentral', label: 'Germany West Central' },
  { code: 'switzerlandnorth', label: 'Switzerland North' },
  { code: 'australiaeast', label: 'Australia East' },
  { code: 'southeastasia', label: 'Southeast Asia' },
  { code: 'eastasia', label: 'East Asia' },
  { code: 'japaneast', label: 'Japan East' },
  { code: 'koreacentral', label: 'Korea Central' },
  { code: 'centralindia', label: 'Central India' },
]

export const AZURE_HD_REGIONS: ReadonlySet<string> = new Set([
  'canadacentral',
  'centralindia',
  'eastus',
  'eastus2',
  'francecentral',
  'southeastasia',
  'swedencentral',
  'westeurope',
  'westus2',
])

export function regionSupportsAzureHd(region: string | null | undefined): boolean {
  return !!region && AZURE_HD_REGIONS.has(region)
}
